version: '3.8'

services:
  database:
    image: postgres:11
    container_name: quartz_test
    restart: on-failure
    healthcheck:
      test: "pg_isready --username=quartz_test-db-user -d quartz_test-db -q"
      timeout: 10s
      retries: 20
    volumes:
      - ./db-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-data/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'quartz_test-db'
      POSTGRES_USER: 'quartz_test-db-user'
      POSTGRES_PASSWORD: 'quartz_test-db-password'
    ports:
      - '5434:5432'

  sbom-quartz1:
    image: sbom-quartz:dev
    environment:
      - ENV=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/quartz_test-db
    ports:
      - "8081:8080"

  sbom-quartz2:
    image: sbom-quartz:dev
    environment:
      - ENV=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/quartz_test-db
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - sbom-quartz1
      - sbom-quartz2